"$schema" = 'https://starship.rs/config-schema.json'

# Configures the format of the prompt.
format = """
[](color_red0)\
$os\
$username\
[](bg:color_orange fg:color_red0)\
$directory\
[](fg:color_orange bg:color_yellow)\
$git_branch\
$git_status\
[](fg:color_yellow bg:color_green)\
$c\
$dotnet\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
$elixir\
$elm\
$gradle\
$julia\
$nim\
$scala\
[](fg:color_green bg:color_cyan)\
$docker_context\
[ ](color_cyan)\
$fill\
([ ](mono4)\
$time\
$battery\
[](mono4))\
$line_break$character"""

# Sets the palette to "one_dark".
palette = 'one_dark'

# Sets the colors of the "one_dark" palette.
[palettes.one_dark]
mono0 = '#dce0e5' # terminal white, matches Zed's terminal.ansi.white
mono1 = '#acb2be' # syntax_fg, matches Zed's editor.foreground
mono2 = '#a9afbc' # matches Zed's text.muted
mono3 = '#5d636f' # matches Zed's syntax comment color
mono4 = '#282c33' # terminal black, matches Zed's terminal.ansi.black
color_red0 = '#d07277' # matches Zed's syntax property and terminal red
color_red1 = '#be5046' # matches Zed's syntax punctuation.special
color_green = '#a1c181' # matches Zed's syntax string color
color_yellow = '#dec184' # matches Zed's syntax constant color (note: dfc184 in syntax)
color_blue = '#74ade8' # matches Zed's syntax attribute and text.accent
color_purple = '#b477cf' # matches Zed's syntax keyword color
color_cyan = '#6eb4bf' # matches Zed's syntax operator and type color
color_orange = '#bf956a' # matches Zed's syntax boolean and number color
syntax_fg = '#acb2be' # matches Zed's editor.foreground
syntax_bg = '#282c33' # matches Zed's editor.background
color_bg2 = '#2f343e' # matches Zed's elevated_surface.background
syntax_gutter = '#4e5a5f' # matches Zed's editor.line_number
syntax_accent = '#74ade8' # matches Zed's text.accent

# Module that displays the current OS.
[os]
disabled = false # Disabled by default
style = "bg:color_red0 fg:syntax_bg"
format = '[ $symbol ]($style)'

# Sets custom symbols for each OS.
[os.symbols]
Alpine = ""
Amazon = ""
Android = "󰀲"
Arch = ""
CentOS = ""
Debian = "󰣚"
EndeavourOS = ""
Fedora = "󰣛"
FreeBSD = "󰣠"
Gentoo = "󰣨"
Illumos = ""
Linux = "󰌽"
Macos = "󰀵"
Manjaro = "󱘊"
Mint = "󰣭"
NixOS = "󱄅"
OpenBSD = ""
openSUSE = ""
Pop = ""
Raspbian = ""
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Redox = "R"
Solus = ""
SUSE = ""
Ubuntu = "󰕈"
Unknown = ""
Windows = "󰍲"

# Module that displays the current username.
[username]
show_always = true
style_user = "bold bg:color_red0 fg:syntax_bg"
style_root = "bold italic bg:color_red0 fg:syntax_bg"
format = '[ $user ]($style)'

# Module that displays the current directory.
[directory]
style = "italic fg:syntax_bg bg:color_orange"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Sets the custom symbols for directories.
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

# Module that displays the current git branch.
[git_branch]
symbol = ""
style = "bg:color_yellow"
format = '[[ $symbol $branch ](fg:syntax_bg bg:color_yellow)]($style)'

# Module that displays the current git status.
[git_status]
style = "bg:color_green"
format = '[[($all_status$ahead_behind )](fg:syntax_bg bg:color_yellow)]($style)'

# Language specific modules
[nodejs]
symbol = ""
style = "bg:color_green"
format = '[[ $symbol( $version) ](fg:syntax_bg bg:color_green)]($style)'

[c]
symbol = " "
style = "bg:color_green"
format = '[[ $symbol( $version) ](fg:syntax_bg bg:color_green)]($style)'

[dotnet]
symbol = "󰪮"
style = "bg:color_green"
format = '[[ $symbol( $version) ](fg:syntax_bg bg:color_green)]($style)'

[rust]
symbol = ""
style = "bg:color_green"
format = '[[ $symbol( $version) ](fg:syntax_bg bg:color_green)]($style)'

[golang]
symbol = ""
style = "bg:color_green"
format = '[[ $symbol( $version) ](fg:syntax_bg bg:color_green)]($style)'

[php]
symbol = " "
style = "bg:color_green"
format = '[[ $symbol( $version) ](fg:syntax_bg bg:color_green)]($style)'

[java]
symbol = " "
style = "bg:color_green"
format = '[[ $symbol( $version) ](fg:syntax_bg bg:color_green)]($style)'

[kotlin]
symbol = " "
style = "bg:color_green"
format = '[[ $symbol( $version) ](fg:syntax_bg bg:color_green)]($style)'

[haskell]
symbol = " "
style = "bg:color_green"
format = '[[ $symbol( $version) ](fg:syntax_bg bg:color_green)]($style)'

[python]
symbol = " "
style = "bg:color_green"
format = '[[ $symbol( $version) ](fg:syntax_bg bg:color_green)]($style)'

[elixir]
symbol = " "
style = "bg:color_green"
format = '[[ $symbol ($version) ](fg:syntax_bg bg:color_green)]($style)'

[elm]
symbol = " "
style = "bg:color_green"
format = '[[ $symbol ($version) ](fg:syntax_bg bg:color_green)]($style)'

[gradle]
symbol = " "
style = "bg:color_green"
format = '[[ $symbol ($version) ](fg:syntax_bg bg:color_green)]($style)'

[julia]
symbol = " "
style = "bg:color_green"
format = '[[ $symbol ($version) ](fg:syntax_bg bg:color_green)]($style)'

[nim]
symbol = "󰆥 "
style = "bg:color_green"
format = '[[ $symbol ($version) ](fg:syntax_bg bg:color_green)]($style)'

[scala]
symbol = " "
style = "bg:color_green"
format = '[[ $symbol ($version) ](fg:syntax_bg bg:color_green)]($style)'

# Module that displays the docker context.
[docker_context]
symbol = " "
style = "bg:mono3"
format = '[[ $symbol( $context) ](fg:syntax_fg bg:mono3)]($style)'

# Module that fills the space between the left and right segments.
[fill]
symbol = " "

# Module that displays the time.
[time]
disabled = false # Disabled by default
use_12hr = true # Disable for 24h format without seconds
style = "bg:mono4"
format = '[[ 󰥔 $time ](fg:syntax_fg bg:mono4)]($style)'

# Module that displays the battery level and status.
[battery]
format = '[$symbol $percentage ]($style)'

# Battery symbols and colors for each threshold.
[[battery.display]]
threshold = 10
style = "bold bg:mono4 fg:color_red1"
discharging_symbol = "󰁺"
charging_symbol = "󰢜"

[[battery.display]]
threshold = 20
style = "bold bg:mono4 fg:color_red0"
discharging_symbol = "󰁻"
charging_symbol = "󰂆"

[[battery.display]]
threshold = 30
style = "bold bg:mono4 fg:color_yellow"
discharging_symbol = "󰁼"
charging_symbol = "󰂇"

[[battery.display]]
threshold = 40
style = "bold bg:mono4 fg:color_yellow"
discharging_symbol = "󰁽"
charging_symbol = "󰂈"

[[battery.display]]
threshold = 50
style = "bold bg:mono4 fg:color_yellow"
discharging_symbol = "󰁾"
charging_symbol = "󰢝"

[[battery.display]]
threshold = 60
style = "bold bg:mono4 fg:color_green"
discharging_symbol = "󰁿"
charging_symbol = "󰂉"

[[battery.display]]
threshold = 70
style = "bold bg:mono4 fg:color_green"
discharging_symbol = "󰂀"
charging_symbol = "󰢞"

[[battery.display]]
threshold = 80
style = "bold bg:mono4 fg:color_green"
discharging_symbol = "󰂁"
charging_symbol = "󰂊"

[[battery.display]]
threshold = 90
style = "bold bg:mono4 fg:color_green"
discharging_symbol = "󰂂"
charging_symbol = "󰂋"

[[battery.display]]
style = "bold bg:mono4 fg:color_green"
discharging_symbol = "󰁹"
charging_symbol = "󰂅"
threshold = 100

# New line character
[character]
success_symbol = '[󰅂](bold fg:syntax_accent)'
error_symbol = '[](bold fg:color_red1)'
vimcmd_symbol = '[󰅁](bold fg:syntax_accent)'
vimcmd_replace_one_symbol = '[󰅁](bold fg:color_purple)'
vimcmd_replace_symbol = '[󰅁](bold fg:color_purple)'
vimcmd_visual_symbol = '[󰅁](bold fg:color_yellow)'
